name: Validación de Script

on:
  push:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Instalar shellcheck
      run: sudo apt-get install shellcheck

    - name: Ejecutar shellcheck
      run: shellcheck script.sh
